namespace Assets.Scripts.Ssar.Combat.Skills
{
	public enum ModifierType
	{
		Knockback = 0,
		Knockdown = 1,
		Stun = 2,
		Shackle = 3,
		MovementSpeed = 4,
		Attack = 5,
		Def = 6,
		Burn = 7,
		CameraFxShake = 8,
		CameraFxSlowMotion = 9,
		CameraFxZoomToTarget = 10,
		Cursed = 11,
		Freeze = 12,
		Scream = 13,
		SoundFx = 14,
		CastSkill = 15,
		PlayVfx = 16,
		HpDropAttackBuff = 17,
		CastBlastWave = 18,
		HpDropUsePotion = 19,
		CastShockwave = 20,
		SoundFxRandomly = 21,
		ColdBurn = 22,
		Shock = 23,
		Bleed = 24,
		HitTargetAttackBuff = 25,
		HitTargetDealDamage = 26,
		HpDropMultipleAttackBuff = 27,
		BeCritDmgReductionBuff = 28,
		BeHitDefBuff = 29,
		HpDropImmuneBuff = 30,
		HpDropHpBuff = 31,
		HpDropAllIn = 32,
		DashSpeedBuff = 33,
		CaskSkillDamageBuff = 34,
		CastReflectAttack = 35,
		EnterRaidBuff = 36,
		CastMagicDamageBlockBuff = 37,
		BuffByPetStats = 38,
		BloodBond = 39,
		Silent = 40,
		DamageReduction = 41,
		Poison = 42,
		Frost = 43,
		Devour = 44,
		CastProjectile = 45,
		AdjustTimeFrame = 46,
		CastSpawnMonster = 47,
		Bubble = 48,
		HP = 49,
		HitTargetInstantKill = 50,
		HitTargetCastSkill = 51
	}
}
