namespace SSAR.Dungeon.HUD
{
	public enum HUDTextType
	{
		DMG = 0,
		CRIT_DMG = 1,
		DMG_ON_CHARACTER = 2,
		EQUIPMENT_NAME_DAMAGED = 3,
		EQUIPMENT_NAME_COMMON = 4,
		EQUIPMENT_NAME_MAGIC = 5,
		EQUIPMENT_NAME_RARE = 6,
		EQUIPMENT_NAME_LEGENDARY = 7,
		IMMUNE = 8,
		HEAL = 9,
		NOTIFY_OBTAIN_EQUIPMENT = 10,
		DMG_MAGICAL = 11,
		DMG_PURE = 12,
		IGNORE_DEF = 13,
		IGNORE_DEF_CRIT = 14,
		DODGE = 15,
		BLOCK_ON_CHARACTER = 16,
		BLOCK_ON_MOB = 17,
		MISS = 18,
		CORPSE_NAME = 19,
		ARENA_TIER_BRONZE = 20,
		ARENA_TIER_SILVER = 21,
		ARENA_TIER_GOLD = 22,
		ARENA_TIER_PLATINUM = 23,
		ARENA_TIER_DIAMOND = 24,
		ARENA_TIER_CHAMPION = 25,
		ARCANE_FORM_DURATION_DEDUCT = 26,
		EQUIPMENT_NAME_ULTIMATE = 27
	}
}
