namespace Assets.Scripts.Core.Skills
{
	public enum BuffType
	{
		Immune = 0,
		MovementSpeed = 1,
		Attack = 2,
		Def = 3,
		Burn = 4,
		Hp = 5,
		ReduceDamageByDistance = 6,
		ReduceDamagePercentage = 7,
		CritDamageOverride = 8,
		AttackOverride = 9,
		CritRateOverride = 10,
		MaxHpOverride = 11,
		DefOverride = 12,
		MagicResistOverride = 13,
		Cursed = 14,
		Freeze = 15,
		Scream = 16,
		Vanish = 17,
		DamageBlock = 18,
		KnockbackWeight = 19,
		KnockdownWeight = 20,
		ColdBurn = 21,
		Shock = 22,
		SkillCritRate = 23,
		Holy = 24,
		Warcry = 25,
		Bless = 26,
		WildHowl = 27,
		Bleed = 28,
		DisableJump = 29,
		DarkArcane = 30,
		CcImmune = 31,
		DamageImmune = 32,
		SkillDamage = 33,
		MagicDamageBlock = 34,
		BloodBond = 35,
		InstantHp = 36,
		Dodge = 37,
		DamageReduction = 38,
		Cooldown = 39,
		HardCcImmune = 40,
		Poison = 41,
		Silent = 42,
		Frost = 43,
		Devour = 44,
		Bubble = 45,
		WarcryFx = 46
	}
}
