namespace SSAR.Dungeon.View
{
	public enum ModifierVisualType
	{
		Invalid = 0,
		MovementSpeed = 1,
		Attack = 2,
		Def = 3,
		Hp = 4,
		Burn = 5,
		CritDmg = 6,
		CritRate = 7,
		MagicResist = 8,
		ReduceDmg = 9,
		Root = 10,
		Stun = 11,
		Shackle = 12,
		Cursed = 13,
		Freeze = 14,
		Pertrified = 15,
		Scream = 16,
		Vanish = 17,
		Immue = 18,
		Immaterial = 19,
		BonusExp = 20,
		BonusSoul = 21,
		BonusItemDrop = 22,
		AutoHeal = 23,
		Blastwave = 24,
		DeadlyHeal = 25,
		LastStand = 26,
		ArenaRuneAttack = 27,
		ArenaRuneArcane = 28,
		ArenaRuneHealth = 29,
		ArenaRuneHaste = 30,
		ArcaneForm = 31,
		InnateFighter = 32,
		Weakness = 33,
		Rage = 34,
		HardMuscle = 35,
		Endurance = 36,
		LastHope = 37,
		NaturalHealing = 38,
		AllIn = 39,
		Mobility = 40,
		MagicArt = 41,
		ReflectAttack = 42,
		LegendaryHunter = 43,
		MagicBarrier = 44,
		BestFriend = 45,
		ChallengeAttack = 46,
		ChallengeDef = 47,
		ChallengeBerserk = 48,
		ChallengeBloodlust = 49,
		ChallengeSurvival = 50,
		ChallengeSacrifice = 51
	}
}
