namespace Ssar.Achievement.Metrics
{
	public enum MetricsList
	{
		DEFEAT_BOSS = 0,
		UPGRADE_ANY_RUNE_OF_ANY_ACTIVE_SKILL_TO_HIGHEST_LEVEL = 1,
		DIE = 2,
		DISCOVER_A_MAP = 3,
		KILL_A_MIMIC = 4,
		UPGRADE_AN_EQUIPMENT_TO_HIGHEST_LEVEL = 5,
		KILL_A_MONSTER = 6,
		COMPLETE_A_MAP_WITH_ALL_3_STAR = 7,
		REACH_AN_ATTACK_POWER_LEVEL = 8,
		REACH_AN_ARMOR_LEVEL = 9,
		REACH_A_HP_LEVEL = 10,
		REACH_A_NUMBER_OF_SOUL = 11,
		WIN_ANY_TOWER_FLOOR = 12,
		REACH_A_MASTERY_LEVEL = 13,
		REFORGE_AN_EQUIPMENT = 14,
		CRAFT_AN_EQUIPMENT = 15,
		OBTAIN_AN_ITEM = 16
	}
}
