namespace SSAR.BattleSystem.System.Arena.Api
{
	public enum StatusCode
	{
		SUCCESS = 1,
		ERROR = 100,
		ERROR_INVALID_OR_MISSING_PARAM = 101,
		ERROR_ALREADY_JOIN_CURRENT_SEASON = 102,
		ERROR_INTERNAL = 103,
		ERROR_TIER_TOO_LOW_FOR_MMR_RANKING = 104,
		ERROR_NOT_JOIN_CURRENT_SEASON = 105,
		ERROR_PREVIOUS_SEASON_NOT_EXISTED = 106,
		ERROR_NOT_JOIN_PREVIOUS_SEASON = 107,
		ERROR_ALREADY_CLAIM_REWARD = 108,
		ERROR_NOT_ELIGIBLE = 109,
		ERROR_MAIN_CHARACTER_DATA_NOT_EXISTED = 110,
		ERROR_SEASON_UNDER_TRANSITION = 111,
		ERROR_INVALID_GAME_VERSION = 112,
		ERROR_UNSUPPORTED_GAME_VERSION = 113
	}
}
