namespace SSAR.BattleSystem.AI
{
	public enum ActionTriggerType
	{
		FUTHER_THAN_RANGE = 0,
		CLOSER_THAN_RANGE = 1,
		DEDUCT_OVER_TIME = 2,
		CLOSER_THAN_RANGE_X = 3,
		AFTER_ACTION = 4,
		CLOSER_THAN_RANGE_X_BUT_OUT_OF_RANGE = 5,
		HP_THRESHOLD = 6,
		HP_LOST = 7,
		FUTHER_THAN_RANGE_X = 8,
		AFTER_TARGET_ACTION = 9,
		NO_TARGET = 10,
		TARGET_ON_AIR = 11,
		ON_EXCUTE_ACTION = 12,
		ON_RUN_ACTION = 13,
		ON_ATTACH_MODIFIER = 14,
		ON_TARGET_BEATTACH_MODIFIER = 15,
		TARGET_HOLD_ATTACK = 16,
		ALWAYS_TRUE = 17,
		AFTER_TARGET_CAST_SKILL = 18,
		IN_TARGET_SKILL_RANGE = 19,
		RESET_POINT_WHEN_ANOTHER_ACTION_AWAKE = 20,
		HP_LOST_IN_TIME = 21,
		ONE_TIME_TRIGGER = 22,
		IN_TARGET_SKILL_PROJECTILE_RANGE = 23,
		TARGET_APPROACHED = 24,
		ON_ENTITY_SPAWN = 25,
		ON_ENTITY_DEATH = 26,
		BOSS_HP_THRESHOLD = 27
	}
}
