using System;

namespace SSAR.BattleSystem.AI
{
	[Serializable]
	public enum MobType
	{
		SCENARIO_NORMAL_MELEE = 0,
		SCENARIO_HARD_MELEE = 1,
		SCENARIO_HELL_MELEE = 2,
		SCENARIO_NORMAL_RANGE = 3,
		SCENARIO_HARD_RANGE = 4,
		SCENARIO_HELL_RANGE = 5,
		SCENARIO_MINIBOSS_NORMAL_MELEE = 6,
		SCENARIO_MINIBOSS_HARD_MELEE = 7,
		SCENARIO_MINIBOSS_HELL_MELEE = 8,
		SCENARIO_MINIBOSS_NORMAL_RANGE = 9,
		SCENARIO_MINIBOSS_HARD_RANGE = 10,
		SCENARIO_MINIBOSS_HELL_RANGE = 11,
		SCENARIO_BOSS_NORMAL_MELEE = 12,
		SCENARIO_BOSS_HARD_MELEE = 13,
		SCENARIO_BOSS_HELL_MELEE = 14,
		SCENARIO_BOSS_NORMAL_RANGE = 15,
		SCENARIO_BOSS_HARD_RANGE = 16,
		SCENARIO_BOSS_HELL_RANGE = 17,
		TOWER1_MELEE = 18,
		TOWER1_RANGE = 19,
		TOWER1_BOSS_FLOOR1TO6_MELEE = 20,
		TOWER1_BOSS_FLOO1TO6_RANGE = 21,
		TOWER1_FINALBOSS = 22,
		TOWER2_FINALBOSS = 23
	}
}
