public enum MusicScene
{
	MAIN = 0,
	WORLDMAP = 1,
	MAP_1 = 2,
	MAP_2 = 3,
	MAP_3 = 4,
	MENU_MEMORYSHARD = 5,
	MEMORYSHARD_DROP_IN_COMBAT = 6,
	NONE = 7,
	CHALLENGE_MAP = 8,
	BLOODYTOWER = 9,
	CHARACTER_SELETION = 10,
	ARENA = 11,
	RAID = 12,
	MAP_4 = 13,
	DAILY_CHALLENGE = 14,
	MAP_5 = 15
}
