namespace SSAR.Equipment.Enum
{
	public enum StatType
	{
		BONUS_ATK = 0,
		BONUS_DEF = 1,
		BONUS_HP = 2,
		BONUS_MAGIC_RESIST = 3,
		BONUS_DAMAGE_BLOCK = 4,
		BONUS_MAGIC_DAMAGE_BARRIER = 5,
		BONUS_MOV_SPD = 6,
		BONUS_ATK_PERCENT = 7,
		BONUS_DEF_PERCENT = 8,
		BONUS_HP_PERCENT = 9,
		BONUS_CRIT_CHANCE = 10,
		BONUS_CRIT_DAMAGE = 11,
		BONUS_DAMAGE_REDUCTION = 12,
		BONUS_ITEM_DROP = 13,
		BONUS_EXP_GAIN = 14,
		BONUS_SOUL_GAIN = 15,
		BONUS_SKILL_DAMAGE = 16,
		BONUS_HP_PER_HIT = 17,
		BONUS_DAMAGE_AGAINST_BOSS = 18,
		BONUS_ATTACK_SPEED = 19,
		BONUS_COOLDOWN_REDUCTION = 20,
		BONUS_DODGE_CHANCE = 21,
		BONUS_BLOCK_CHANCE = 22,
		BONUS_BOSS_DAMAGE_REDUCTION = 23,
		BONUS_HP_PER_SECOND = 24,
		BONUS_LIFE_STEAL = 25,
		BONUS_HP_PERCENT_PER_KILL = 26,
		BONUS_SKILL_CRIT_CHANCE = 27,
		BONUS_SKILL_CRIT_DAMAGE = 28,
		BONUS_DAMAGE_PVP = 29
	}
}
